### ISSUE TITLE
🚀  Adding a Feature: Feed

### ISSUE THREAD

**Issue by paOmer** [redhat-beyond/JobSeeker#26]
Create a feed, the feed is the project main page, it would contain posts from different users.
The feed app will contain posts and comments data models that need to be set up.
The following tasks should be completed:

- [x] Create a feed app
- [x] Create a post data model
- [x] Create a comment data model
- [x] Add test for the data models
- [x] Populate the DB

The post and comment data models should look like the following ERD:

[![](https://mermaid.ink/img/pako:eNqtVNtuozAQ_ZWRn7pS8wN5qxKyqnqLklT7ggQODMVd44lss90q4d87NqSlt5eoCIHxmTlzOWP2oqASxVSgnSv5YGWTGuDrfp2s4HCYTGgPy7v1BqbwZJVH18P9MwL7fh0u560yD3A5h-UVpOI3GrTSY8k7qfhktrNYoUVToMvYZRFcctNqnYOqwNfKAd-GPEh4pO2EKjYf82yJNErDVhnjWcSZg53zSmqHOZOggfxdoDIPrH2cL5KSra_JvuZz75jyffazWtqFQl2CV17jGzDnUjeqwR4s-SvbkQvlpyJgQBWEDQ4z5tvgf9-7FGQ8Gv8GhegX1spn0OovOubRyvnA0zLi4KmmiJSh0Mh9JO5GAg0qzu5ubpLbIGQt3Rgmhg-wXCWLZJXczpI1m6Si4ai1_IdwdhRjyfyhdyM1fh3jDeQnz0JBTcOlZztpw-vDOMgt9_mLAeKEPnr8qVnpPt-BE-LSGCxCdE8nif6z2nafDlFHUaPry6vY_leF-o2T2xrG5LuyOnEuGrSNVCUf_xgiFTxHDbc6DECJlWx1nKhg2u5C1UmpPFkxjefrXHDjaP1sCjH1tsWj0fAjGay6F9oaX1M)](https://mermaid.live/edit#pako:eNqtVNtuozAQ_ZWRn7pS8wN5qxKyqnqLklT7ggQODMVd44lss90q4d87NqSlt5eoCIHxmTlzOWP2oqASxVSgnSv5YGWTGuDrfp2s4HCYTGgPy7v1BqbwZJVH18P9MwL7fh0u560yD3A5h-UVpOI3GrTSY8k7qfhktrNYoUVToMvYZRFcctNqnYOqwNfKAd-GPEh4pO2EKjYf82yJNErDVhnjWcSZg53zSmqHOZOggfxdoDIPrH2cL5KSra_JvuZz75jyffazWtqFQl2CV17jGzDnUjeqwR4s-SvbkQvlpyJgQBWEDQ4z5tvgf9-7FGQ8Gv8GhegX1spn0OovOubRyvnA0zLi4KmmiJSh0Mh9JO5GAg0qzu5ubpLbIGQt3Rgmhg-wXCWLZJXczpI1m6Si4ai1_IdwdhRjyfyhdyM1fh3jDeQnz0JBTcOlZztpw-vDOMgt9_mLAeKEPnr8qVnpPt-BE-LSGCxCdE8nif6z2nafDlFHUaPry6vY_leF-o2T2xrG5LuyOnEuGrSNVCUf_xgiFTxHDbc6DECJlWx1nKhg2u5C1UmpPFkxjefrXHDjaP1sCjH1tsWj0fAjGay6F9oaX1M)

**Comment by amittcohen** [comment]
What is the 'comment_parent_ID'?
