### ISSUE TITLE
:rocket: Adding a feature: Login page

### ISSUE THREAD

**Issue by amittcohen** [redhat-beyond/JobSeeker#31]
- [x] Create some sample users to test login functionality
- [x] Create login page html and backend
- [x] Create tests for the login page

**Comment by taljacob2** [comment]
@amittcohen Hi, please edit this issue's title to:
 ```
:rocket: Adding a feature: Login page
```
So it will look like this:

:rocket: Adding a feature: Login page

**Comment by amittcohen** [comment]
> @amittcohen Hi, please edit this issue's title to:
> 
> ```
> :rocket: Adding a feature: Login page
> ```
> 
> So it will look like this:
> 
> 🚀 Adding a feature: Login page

done
