### ISSUE TITLE
🏇 Update Links In Base Template

### ISSUE THREAD

**Issue by paOmer** [redhat-beyond/JobSeeker#74]
The links to different pages in the base template need's to be updated to direct to the correct pages.
The base template located at `jobseeker/templates/jobseeker/base_template.html`.

The links to be updated are:

- Logo should direct to feed
- Home should direct to feed
- Jobs should direct to job board
- Login should direct to login page
- Register should be removed

**Comment by amittcohen** [comment]
Done in pull requests #101 and #102 except for the job board, the has no "urls.py" file. 
I'll open an issue for that
